spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:taskmanager
    driver-class-name: org.h2.Driver
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
